spring:
  application:
    name: greeting-service
  config:
    import: "optional:configserver:"
greeting-service:
  greeting: "Hello"
  default-value: "Momo!"
management:
  endpoints:
    web:
      exposure:
        include: "*"
